# Generated by Django 3.0.5 on 2020-04-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200430_1332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
