# Generated by Django 3.0.5 on 2020-04-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='verified',
        ),
    ]
