# Generated by Django 3.0.5 on 2020-05-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='challenger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
