# Generated by Django 3.0.5 on 2020-04-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Dashboard',
        ),
    ]
