# Generated by Django 3.0.5 on 2020-04-26 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200422_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='beginning',
            field=models.DateField(default=datetime.datetime(2020, 4, 26, 19, 26, 41, 203430)),
        ),
    ]
