# Generated by Django 3.0.5 on 2020-04-26 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboard_beginning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='beginning',
            field=models.DateField(default=datetime.datetime(2020, 4, 26, 19, 27, 34, 500754, tzinfo=utc)),
        ),
    ]
