# Generated by Django 3.0.5 on 2020-04-28 00:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200426_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='author',
            field=models.TextField(default='rodmarzz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='beginning',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 0, 12, 36, 898095, tzinfo=utc)),
        ),
    ]
