# Generated by Django 3.0.5 on 2020-04-28 00:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200428_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='beginning',
            field=models.DateField(default=datetime.datetime(2020, 4, 28, 0, 16, 23, 19588, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
