# Generated by Django 3.0.5 on 2020-05-02 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200428_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('points', models.IntegerField(db_index=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Dashboard')),
            ],
        ),
    ]
