# Generated by Django 3.0.5 on 2020-05-02 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200502_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='points',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='username',
            field=models.CharField(db_index=True, default=None, max_length=150),
        ),
    ]
