# Generated by Django 3.0.5 on 2020-05-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200502_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='max_daily_uploads',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='wait_time_uploads',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='participants',
            field=models.IntegerField(default=0),
        ),
    ]
