# Generated by Django 3.0.5 on 2020-05-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20200502_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='test',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='train',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
