# Generated by Django 3.0.5 on 2020-05-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20200505_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='test',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='train',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
