# Generated by Django 3.0.5 on 2020-05-05 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20200505_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='test',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='train',
        ),
    ]
