# Generated by Django 3.0.5 on 2020-05-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20200505_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='test',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
