# Generated by Django 3.0.5 on 2020-05-05 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20200505_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='test',
        ),
    ]
