# Generated by Django 3.0.5 on 2020-05-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_dashboard_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='train',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
