# Generated by Django 3.0.5 on 2020-05-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_dashboard_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='private',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
