# Generated by Django 3.0.5 on 2020-05-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_ranking_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='submission',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
